version: "3.8"
services:
  postgres:
    image: postgres
    working_dir: /home/node/app
    env_file:
      - .env
    environment:
      # Database 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_DEV}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./:/home/node/app
    ports:
      - "5432:5432"